spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:    #这里的意思是：Query = 网址 ，且网址包含正则baidu
            - Query=url,baidu
        - id: qq_route
          uri: http://qq.com
          predicates:
            - Query=url,qq
        - id: product_route
          uri: lb://guli-product
          predicates:
            - Path=/api/guliproduct/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://guli-member
          predicates:
            - Path=/api/gulimember/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://guli-ware
          predicates:
            - Path=/api/guliware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: oss_routes
          uri: lb://guli-module
          predicates:
            - Path=/api/module/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast  #lb代表负载均衡到renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: guli_host_route  #负载均衡路由
          uri: lb://guli-product
          predicates:
            - Host=pro.guli.com,item.guli.com
        - id: guli_search_route
          uri: lb://guli-search
          predicates:
            - Host=search.guli.com
        - id: guli_auth_route
          uri: lb://guli-authServer
          predicates:
            - Host=auth.guli.com
        - id: guli_cart_route
          uri: lb://guli-cart
          predicates:
            - Host=cart.guli.com
        - id: guli_order_route
          uri: lb://guli-order
          predicates:
            - Host=order.guli.com
        - id: guli_member_route
          uri: lb://guli-member
          predicates:
            - Host=member.guli.com




#前端项目发送请求，都带上/api 前缀的，都路由到renren-fast
# http://localhost:88/api/captcha.jpg
  #而renren-fast正常访问验证码的路径是：http:localhost:8080/captcha.jpg
  #所以我们应该对路径进行重写操作，保证能路由到正确的地址
